package com.yc.TCMail.bean;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addr
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.level
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.name
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.phone
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.detailaddr
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String detailaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.recvaddr
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String recvaddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addr
     *
     * @return the value of address.addr
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addr
     *
     * @param addr the value for address.addr
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.level
     *
     * @return the value of address.level
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.level
     *
     * @param level the value for address.level
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.name
     *
     * @return the value of address.name
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.name
     *
     * @param name the value for address.name
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.phone
     *
     * @return the value of address.phone
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.phone
     *
     * @param phone the value for address.phone
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.uid
     *
     * @return the value of address.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.uid
     *
     * @param uid the value for address.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.detailaddr
     *
     * @return the value of address.detailaddr
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getDetailaddr() {
        return detailaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.detailaddr
     *
     * @param detailaddr the value for address.detailaddr
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setDetailaddr(String detailaddr) {
        this.detailaddr = detailaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.recvaddr
     *
     * @return the value of address.recvaddr
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getRecvaddr() {
        return recvaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.recvaddr
     *
     * @param recvaddr the value for address.recvaddr
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setRecvaddr(String recvaddr) {
        this.recvaddr = recvaddr;
    }
}

