package com.yc.TCMail.bean;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.gid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.id
     *
     * @return the value of car.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.id
     *
     * @param id the value for car.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.gid
     *
     * @return the value of car.gid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.gid
     *
     * @param gid the value for car.gid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.uid
     *
     * @return the value of car.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.uid
     *
     * @param uid the value for car.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}