package com.yc.TCMail.bean;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.atti
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer atti;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commenttime
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String commenttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.gfit
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer gfit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.img
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.msg
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.satisf
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer satisf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.see
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String see;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.speed
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer speed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.watti
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer watti;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.atti
     *
     * @return the value of comment.atti
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getAtti() {
        return atti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.atti
     *
     * @param atti the value for comment.atti
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setAtti(Integer atti) {
        this.atti = atti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commenttime
     *
     * @return the value of comment.commenttime
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getCommenttime() {
        return commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commenttime
     *
     * @param commenttime the value for comment.commenttime
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setCommenttime(String commenttime) {
        this.commenttime = commenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.gfit
     *
     * @return the value of comment.gfit
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getGfit() {
        return gfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.gfit
     *
     * @param gfit the value for comment.gfit
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setGfit(Integer gfit) {
        this.gfit = gfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.img
     *
     * @return the value of comment.img
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.img
     *
     * @param img the value for comment.img
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.msg
     *
     * @return the value of comment.msg
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.msg
     *
     * @param msg the value for comment.msg
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.satisf
     *
     * @return the value of comment.satisf
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getSatisf() {
        return satisf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.satisf
     *
     * @param satisf the value for comment.satisf
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setSatisf(Integer satisf) {
        this.satisf = satisf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.see
     *
     * @return the value of comment.see
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getSee() {
        return see;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.see
     *
     * @param see the value for comment.see
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setSee(String see) {
        this.see = see;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.speed
     *
     * @return the value of comment.speed
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.speed
     *
     * @param speed the value for comment.speed
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setSpeed(Integer speed) {
        this.speed = speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.uid
     *
     * @return the value of comment.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.uid
     *
     * @param uid the value for comment.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.watti
     *
     * @return the value of comment.watti
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getWatti() {
        return watti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.watti
     *
     * @param watti the value for comment.watti
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setWatti(Integer watti) {
        this.watti = watti;
    }
}