package com.yc.TCMail.bean;

public class Favorite {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.ftime
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String ftime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.goodsid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.shopid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.id
     *
     * @return the value of favorite.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.id
     *
     * @param id the value for favorite.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.ftime
     *
     * @return the value of favorite.ftime
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getFtime() {
        return ftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.ftime
     *
     * @param ftime the value for favorite.ftime
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setFtime(String ftime) {
        this.ftime = ftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.goodsid
     *
     * @return the value of favorite.goodsid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.goodsid
     *
     * @param goodsid the value for favorite.goodsid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.shopid
     *
     * @return the value of favorite.shopid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.shopid
     *
     * @param shopid the value for favorite.shopid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.uid
     *
     * @return the value of favorite.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.uid
     *
     * @param uid the value for favorite.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}