package com.yc.TCMail.bean;

public class Goodsmsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsmsg.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsmsg.color
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsmsg.sid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsmsg.size
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsmsg.tid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsmsg.id
     *
     * @return the value of goodsmsg.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsmsg.id
     *
     * @param id the value for goodsmsg.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsmsg.color
     *
     * @return the value of goodsmsg.color
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsmsg.color
     *
     * @param color the value for goodsmsg.color
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsmsg.sid
     *
     * @return the value of goodsmsg.sid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsmsg.sid
     *
     * @param sid the value for goodsmsg.sid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsmsg.size
     *
     * @return the value of goodsmsg.size
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsmsg.size
     *
     * @param size the value for goodsmsg.size
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsmsg.tid
     *
     * @return the value of goodsmsg.tid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsmsg.tid
     *
     * @param tid the value for goodsmsg.tid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}