package com.yc.TCMail.bean;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.color
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.commnum
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer commnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.image
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.num
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.point
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.size
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.tid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.color
     *
     * @return the value of goods.color
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.color
     *
     * @param color the value for goods.color
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.commnum
     *
     * @return the value of goods.commnum
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getCommnum() {
        return commnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.commnum
     *
     * @param commnum the value for goods.commnum
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setCommnum(Integer commnum) {
        this.commnum = commnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.image
     *
     * @return the value of goods.image
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.image
     *
     * @param image the value for goods.image
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.num
     *
     * @return the value of goods.num
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.num
     *
     * @param num the value for goods.num
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.point
     *
     * @return the value of goods.point
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.point
     *
     * @param point the value for goods.point
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sid
     *
     * @return the value of goods.sid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sid
     *
     * @param sid the value for goods.sid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.size
     *
     * @return the value of goods.size
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.size
     *
     * @param size the value for goods.size
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.tid
     *
     * @return the value of goods.tid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.tid
     *
     * @param tid the value for goods.tid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}