package com.yc.TCMail.bean;

public class Gtype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gtype.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gtype.name
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gtype.pid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gtype.id
     *
     * @return the value of gtype.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gtype.id
     *
     * @param id the value for gtype.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gtype.name
     *
     * @return the value of gtype.name
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gtype.name
     *
     * @param name the value for gtype.name
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gtype.pid
     *
     * @return the value of gtype.pid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gtype.pid
     *
     * @param pid the value for gtype.pid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}