package com.yc.TCMail.bean;

public class Image {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.gid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.path
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.id
     *
     * @return the value of image.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.id
     *
     * @param id the value for image.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.gid
     *
     * @return the value of image.gid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.gid
     *
     * @param gid the value for image.gid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.path
     *
     * @return the value of image.path
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.path
     *
     * @param path the value for image.path
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setPath(String path) {
        this.path = path;
    }
}