package com.yc.TCMail.bean;

public class Point {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.num
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.id
     *
     * @return the value of point.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.id
     *
     * @param id the value for point.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.num
     *
     * @return the value of point.num
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.num
     *
     * @param num the value for point.num
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point.uid
     *
     * @return the value of point.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point.uid
     *
     * @param uid the value for point.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}