package com.yc.TCMail.bean;

public class Return {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return.date
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return.money
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return.oid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return.reason
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return.statu
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String statu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return.descr
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String descr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return.rimage
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String rimage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return.id
     *
     * @return the value of return.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return.id
     *
     * @param id the value for return.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return.date
     *
     * @return the value of return.date
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return.date
     *
     * @param date the value for return.date
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return.money
     *
     * @return the value of return.money
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return.money
     *
     * @param money the value for return.money
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return.oid
     *
     * @return the value of return.oid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return.oid
     *
     * @param oid the value for return.oid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return.reason
     *
     * @return the value of return.reason
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return.reason
     *
     * @param reason the value for return.reason
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return.statu
     *
     * @return the value of return.statu
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getStatu() {
        return statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return.statu
     *
     * @param statu the value for return.statu
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setStatu(String statu) {
        this.statu = statu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return.descr
     *
     * @return the value of return.descr
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return.descr
     *
     * @param descr the value for return.descr
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return.rimage
     *
     * @return the value of return.rimage
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getRimage() {
        return rimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return.rimage
     *
     * @param rimage the value for return.rimage
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setRimage(String rimage) {
        this.rimage = rimage;
    }
}