package com.yc.TCMail.bean;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.addr
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.bustime
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String bustime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.level
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.name
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.type
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.id
     *
     * @return the value of shop.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.id
     *
     * @param id the value for shop.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.addr
     *
     * @return the value of shop.addr
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.addr
     *
     * @param addr the value for shop.addr
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.bustime
     *
     * @return the value of shop.bustime
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getBustime() {
        return bustime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.bustime
     *
     * @param bustime the value for shop.bustime
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setBustime(String bustime) {
        this.bustime = bustime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.level
     *
     * @return the value of shop.level
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.level
     *
     * @param level the value for shop.level
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.name
     *
     * @return the value of shop.name
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.name
     *
     * @param name the value for shop.name
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.type
     *
     * @return the value of shop.type
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.type
     *
     * @param type the value for shop.type
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop.uid
     *
     * @return the value of shop.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop.uid
     *
     * @param uid the value for shop.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}