package com.yc.TCMail.bean;

public class Uorder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uorder.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uorder.aid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uorder.orderstatu
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String orderstatu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uorder.ordertime
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uorder.paystatu
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String paystatu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uorder.paytype
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String paytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uorder.tcomp
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String tcomp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uorder.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uorder.visiable
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String visiable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uorder.recivetime
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private String recivetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uorder.totalprice
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    private Double totalprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uorder.id
     *
     * @return the value of uorder.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uorder.id
     *
     * @param id the value for uorder.id
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uorder.aid
     *
     * @return the value of uorder.aid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uorder.aid
     *
     * @param aid the value for uorder.aid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uorder.orderstatu
     *
     * @return the value of uorder.orderstatu
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getOrderstatu() {
        return orderstatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uorder.orderstatu
     *
     * @param orderstatu the value for uorder.orderstatu
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setOrderstatu(String orderstatu) {
        this.orderstatu = orderstatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uorder.ordertime
     *
     * @return the value of uorder.ordertime
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uorder.ordertime
     *
     * @param ordertime the value for uorder.ordertime
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setOrdertime(String ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uorder.paystatu
     *
     * @return the value of uorder.paystatu
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getPaystatu() {
        return paystatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uorder.paystatu
     *
     * @param paystatu the value for uorder.paystatu
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setPaystatu(String paystatu) {
        this.paystatu = paystatu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uorder.paytype
     *
     * @return the value of uorder.paytype
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uorder.paytype
     *
     * @param paytype the value for uorder.paytype
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uorder.tcomp
     *
     * @return the value of uorder.tcomp
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getTcomp() {
        return tcomp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uorder.tcomp
     *
     * @param tcomp the value for uorder.tcomp
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setTcomp(String tcomp) {
        this.tcomp = tcomp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uorder.uid
     *
     * @return the value of uorder.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uorder.uid
     *
     * @param uid the value for uorder.uid
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uorder.visiable
     *
     * @return the value of uorder.visiable
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getVisiable() {
        return visiable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uorder.visiable
     *
     * @param visiable the value for uorder.visiable
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setVisiable(String visiable) {
        this.visiable = visiable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uorder.recivetime
     *
     * @return the value of uorder.recivetime
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public String getRecivetime() {
        return recivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uorder.recivetime
     *
     * @param recivetime the value for uorder.recivetime
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setRecivetime(String recivetime) {
        this.recivetime = recivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uorder.totalprice
     *
     * @return the value of uorder.totalprice
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public Double getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uorder.totalprice
     *
     * @param totalprice the value for uorder.totalprice
     *
     * @mbg.generated Mon May 06 20:08:23 CST 2019
     */
    public void setTotalprice(Double totalprice) {
        this.totalprice = totalprice;
    }
}