package com.yc.TCMail.dao;

import com.yc.TCMail.bean.Comment;
import com.yc.TCMail.bean.CommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    long countByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int deleteByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    List<Comment> selectByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    Comment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int updateByExampleSelective(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int updateByExample(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int updateByPrimaryKey(Comment record);
}