package com.yc.TCMail.dao;

import com.yc.TCMail.bean.Goods;
import com.yc.TCMail.bean.GoodsExample;

import java.util.ArrayList;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;


public interface GoodsMapper {
	
	List<Goods> selectWithTime();
	List<Goods> selectGoodsBySunId(@Param("id")Integer id);
	Goods selectGoods(Integer id);
	List<Goods> selectGoodsByTid(Integer id);
	


	Goods selectGoods();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
<<<<<<< HEAD
     * @mbg.generated Sat May 11 14:59:10 CST 2019
=======
     * @mbg.generated Sun May 12 09:52:27 CST 2019
>>>>>>> refs/remotes/origin/master
     */

    long countByExample(GoodsExample example);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
<<<<<<< HEAD
     * @mbg.generated Sat May 11 14:59:10 CST 2019
=======
     * @mbg.generated Sun May 12 09:52:27 CST 2019
>>>>>>> refs/remotes/origin/master
     */

    int deleteByExample(GoodsExample example);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
<<<<<<< HEAD
     * @mbg.generated Sat May 11 14:59:10 CST 2019
=======
     * @mbg.generated Sun May 12 09:52:27 CST 2019
>>>>>>> refs/remotes/origin/master
     */

    int deleteByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
<<<<<<< HEAD
     * @mbg.generated Sat May 11 14:59:10 CST 2019
=======
     * @mbg.generated Sun May 12 09:52:27 CST 2019
>>>>>>> refs/remotes/origin/master
     */

    int insert(Goods record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
<<<<<<< HEAD
     * @mbg.generated Sat May 11 14:59:10 CST 2019
=======
     * @mbg.generated Sun May 12 09:52:27 CST 2019
>>>>>>> refs/remotes/origin/master
     */

    int insertSelective(Goods record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
<<<<<<< HEAD
     * @mbg.generated Sat May 11 14:59:10 CST 2019
=======
     * @mbg.generated Sun May 12 09:52:27 CST 2019
>>>>>>> refs/remotes/origin/master
     */
  

    List<Goods> selectByExample(GoodsExample example);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
<<<<<<< HEAD
     * @mbg.generated Sat May 11 14:59:10 CST 2019
=======
     * @mbg.generated Sun May 12 09:52:27 CST 2019
>>>>>>> refs/remotes/origin/master
     */

    Goods selectByPrimaryKey(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
<<<<<<< HEAD
     * @mbg.generated Sat May 11 14:59:10 CST 2019
=======
     * @mbg.generated Sun May 12 09:52:27 CST 2019
>>>>>>> refs/remotes/origin/master
     */

    int updateByExampleSelective(@Param("record") Goods record, @Param("example") GoodsExample example);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
<<<<<<< HEAD
     * @mbg.generated Sat May 11 14:59:10 CST 2019
=======
     * @mbg.generated Sun May 12 09:52:27 CST 2019
>>>>>>> refs/remotes/origin/master
     */

    int updateByExample(@Param("record") Goods record, @Param("example") GoodsExample example);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
<<<<<<< HEAD
     * @mbg.generated Sat May 11 14:59:10 CST 2019
=======
     * @mbg.generated Sun May 12 09:52:27 CST 2019
>>>>>>> refs/remotes/origin/master
     */

    int updateByPrimaryKeySelective(Goods record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
<<<<<<< HEAD
     * @mbg.generated Sat May 11 14:59:10 CST 2019
=======
     * @mbg.generated Sun May 12 09:52:27 CST 2019
>>>>>>> refs/remotes/origin/master
     */

    int updateByPrimaryKey(Goods record);
}