package com.yc.TCMail.dao;

import com.yc.TCMail.bean.Return;
import com.yc.TCMail.bean.ReturnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    long countByExample(ReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int deleteByExample(ReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int insert(Return record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int insertSelective(Return record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    List<Return> selectByExample(ReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    Return selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int updateByExampleSelective(@Param("record") Return record, @Param("example") ReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int updateByExample(@Param("record") Return record, @Param("example") ReturnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int updateByPrimaryKeySelective(Return record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table return
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int updateByPrimaryKey(Return record);
}