package com.yc.TCMail.dao;

import com.yc.TCMail.bean.Retgoods;
import com.yc.TCMail.bean.RetgoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Retgoods
     *
     * @mbg.generated Fri May 10 10:01:50 CST 2019
     */
    long countByExample(RetgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Retgoods
     *
     * @mbg.generated Fri May 10 10:01:50 CST 2019
     */
    int deleteByExample(RetgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Retgoods
     *
     * @mbg.generated Fri May 10 10:01:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Retgoods
     *
     * @mbg.generated Fri May 10 10:01:50 CST 2019
     */
    int insert(Retgoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Retgoods
     *
     * @mbg.generated Fri May 10 10:01:50 CST 2019
     */
    int insertSelective(Retgoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Retgoods
     *
     * @mbg.generated Fri May 10 10:01:50 CST 2019
     */
    List<Retgoods> selectByExample(RetgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Retgoods
     *
     * @mbg.generated Fri May 10 10:01:50 CST 2019
     */
    Retgoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Retgoods
     *
     * @mbg.generated Fri May 10 10:01:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") Retgoods record, @Param("example") RetgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Retgoods
     *
     * @mbg.generated Fri May 10 10:01:50 CST 2019
     */
    int updateByExample(@Param("record") Retgoods record, @Param("example") RetgoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Retgoods
     *
     * @mbg.generated Fri May 10 10:01:50 CST 2019
     */
    int updateByPrimaryKeySelective(Retgoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Retgoods
     *
     * @mbg.generated Fri May 10 10:01:50 CST 2019
     */
    int updateByPrimaryKey(Retgoods record);
}