package com.yc.TCMail.dao;

import com.yc.TCMail.bean.Shop;
import com.yc.TCMail.bean.ShopExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    long countByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int deleteByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int insert(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int insertSelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    List<Shop> selectByExample(ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    Shop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int updateByExampleSelective(@Param("record") Shop record, @Param("example") ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int updateByExample(@Param("record") Shop record, @Param("example") ShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int updateByPrimaryKeySelective(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
<<<<<<< HEAD
     * @mbg.generated Mon May 06 20:08:23 CST 2019
=======
     * @mbg.generated Mon May 06 17:25:16 CST 2019
>>>>>>> refs/remotes/origin/master
     */
    int updateByPrimaryKey(Shop record);
}